Mobile version menu designe and make it functional with JavaScript
MuhammadUsmanAslam/Portfolio pull request #10
Opened 2023-01-30 20:29 UTC by MuhammadUsmanAslam

- Mobile menu designed with HTML CSS and made functional with JavaScript
- Updated Linters for JavaScript

2023-01-30 20:48 UTC, GzimAsani requested changes
### Hello @MuhammadUsmanAslam                             :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with creating the hamburger and it's functionality, it works great :+1: 

 ## Required Changes 
- [ ] Check the comments below :arrow_double_down: 


 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-30 20:48 UTC, GzimAsani commented on main.js
> +  }
- [ ] When the hamburger button is clicked and menu appears the background should be blur, kindly check the design _PS: You can make background blur similar to this on CSS **filter: blur(8px);**_
![image](https://user-images.githubusercontent.com/62705947/215590349-09c11a93-e06e-44c4-afa2-9cc58bbc8c51.png)
![image](https://user-images.githubusercontent.com/62705947/215590404-06fde108-a5f0-4edf-82c3-1773abcfdf62.png)

2023-01-30 20:48 UTC, GzimAsani commented on README.md
>  - Twitter: [@twitterhandle](https://twitter.com/M_Usman_Aslam)
-  [ ] Under the USAGE section mention how can a user run your project IE clicking live on vs code

2023-01-30 20:48 UTC, GzimAsani commented on README.md
>  - Twitter: [@twitterhandle](https://twitter.com/M_Usman_Aslam)
- [ ] Please either update or remove the FAQ section 
![image](https://user-images.githubusercontent.com/62705947/215590870-811bf1e9-95e5-4202-b8f4-cbff7849bc91.png)

2023-01-30 20:48 UTC, GzimAsani commented on README.md
>  - Twitter: [@twitterhandle](https://twitter.com/M_Usman_Aslam)
- [ ] Please fill these sections, your readme will look more professional 
![image](https://user-images.githubusercontent.com/62705947/215591023-dcc0ab75-3405-4f03-9a78-1277eee93b9d.png)

2023-01-30 20:48 UTC, GzimAsani commented on README.md
>  - Twitter: [@twitterhandle](https://twitter.com/M_Usman_Aslam)
- [ ] Remove this description please

2023-01-30 20:48 UTC, GzimAsani commented on style.css
> +  display: flex;
- [ ] You have used `display: flex` 18 times which means you are repeating yourself a lot and that is bad CSS practice. I would suggest you create a class with display: flex in it and use it at the HTML components that you need 
![image](https://user-images.githubusercontent.com/62705947/215591435-a5e24085-5ec4-412f-9292-a0ac3d818eb8.png)

2023-01-31 09:47 UTC, binhussen requested changes
Hi @MuhammadUsmanAslam , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 09:47 UTC, binhussen commented on style.css
> +}
- Great job implementing previous code reviewer suggestions,👍 I think you missed the desktop version of your navigation, when updating other things , please fix it for better UI 👌



| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://user-images.githubusercontent.com/52010789/215725472-410f81e9-a3c0-4bcf-9c9b-1eef361fd658.png" width="600">|<img src="https://user-images.githubusercontent.com/52010789/215725466-adc1f2b9-2900-4c14-8ea4-b52a2c278713.png" width="600">|


😎️

🤝️

2023-01-31 10:20 UTC, Olamarx approved these changes
Hi @MuhammadUsmanAslam,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 10:22 UTC, merged